Need to have a TPU go to edit and then notebook settings and click TPU V2. It's a roulette hopefully you get one, just have to keep retrying to connect and eventually you get one

In [1]:
import jax
jax.distributed.initialize()

In [2]:
jax.device_count()

8

In [4]:
import jax.numpy as jnp
x = jnp.arange(3 * 2 * 2.).reshape((3, 2, 2))
y = jnp.arange(3 * 2 * 2.).reshape((3, 2, 2)) ** 2
out = jax.pmap(jnp.dot)(x, y)
print(out)

[[[   4.    9.]
  [  12.   29.]]

 [[ 244.  345.]
  [ 348.  493.]]

 [[1412. 1737.]
  [1740. 2141.]]]


In [24]:
def add(x, y):
  return x + y
j = jax.jit(add).lower(2,2)
k = jax.jit(jnp.dot).lower(2,2)
print(k.as_text())

module @jit_dot attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<i32> {mhlo.layout_mode = "default"}, %arg1: tensor<i32> {mhlo.layout_mode = "default"}) -> (tensor<i32> {jax.result_info = "", mhlo.layout_mode = "default"}) {
    %0 = stablehlo.convert %arg0 : tensor<i32>
    %1 = stablehlo.convert %arg1 : tensor<i32>
    %2 = stablehlo.multiply %0, %1 : tensor<i32>
    %3 = stablehlo.convert %2 : tensor<i32>
    return %3 : tensor<i32>
  }
}



In [23]:
print(jax.jit(jax.pmap(jnp.dot)).lower(x,y).as_text())

module @jit_dot attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 3 : i32} {
  func.func public @main(%arg0: tensor<3x2x2xf32> {mhlo.layout_mode = "default"}, %arg1: tensor<3x2x2xf32> {mhlo.layout_mode = "default"}) -> (tensor<3x2x2xf32> {jax.result_info = "", mhlo.layout_mode = "default"}) {
    %0 = stablehlo.constant dense<0> : tensor<ui32>
    %1 = stablehlo.constant dense<1> : tensor<ui32>
    %2 = stablehlo.constant dense<3> : tensor<ui32>
    %3 = stablehlo.replica_id : tensor<ui32>
    %4 = stablehlo.divide %3, %1 : tensor<ui32>
    %5 = stablehlo.remainder %4, %2 : tensor<ui32>
    %6 = stablehlo.dynamic_slice %arg0, %5, %0, %0, sizes = [1, 2, 2] : (tensor<3x2x2xf32>, tensor<ui32>, tensor<ui32>, tensor<ui32>) -> tensor<1x2x2xf32>
    %7 = stablehlo.reshape %6 : (tensor<1x2x2xf32>) -> tensor<2x2xf32>
    %8 = stablehlo.constant dense<0> : tensor<ui32>
    %9 = stablehlo.constant dense<1> : tensor<ui32>
    %10 = stablehlo.constant dense<3> : tensor<ui32>
    %11 = 

/usr/local/lib/python3.10/dist-packages/jax/_src/interpreters/pxla.py:1858: UserWarning: The jitted function dot includes a pmap. Using jit-of-pmap can lead to inefficient data movement, as the outer jit does not preserve sharded data representations and instead collects input and output arrays onto a single device. Consider removing the outer jit unless you know what you're doing. See https://github.com/google/jax/issues/2926.
  warnings.warn(
